version: '3'
services:
    client:
        image: mikedee254/client:1.0
        restart: always
        ports:
            - "3000:3000"
        #working_dir: /client
        volumes:
            - ./client:/client
            - /client/node_modules
        depends_on:
            - backend
        entrypoint: ["npm","start"]
        networks:
            - yolonetwork
    backend:
        image: mikedee254/backend:1.0
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/backend
            - /backend/node_modules
        depends_on:
            - mongodb
        networks:
            - yolonetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        networks:
            - yolonetwork

networks:
    yolonetwork:
        driver: bridge